/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommandPalette: typeof import('./components/CommandPalette.vue')['default']
    CreateTaskModal: typeof import('./components/CreateTaskModal.vue')['default']
    DecisionQueueList: typeof import('./components/DecisionQueueList.vue')['default']
    EChart: typeof import('./components/EChart.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    KpiCard: typeof import('./components/KpiCard.vue')['default']
    MetricBar: typeof import('./components/MetricBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    QuickActions: typeof import('./components/QuickActions.vue')['default']
    ReceiptOcrModal: typeof import('./components/ReceiptOcrModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./components/SectionCard.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    StatusPill: typeof import('./components/StatusPill.vue')['default']
    TaskDetailDrawer: typeof import('./components/TaskDetailDrawer.vue')['default']
    TaskRow: typeof import('./components/TaskRow.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
